server:
  port: 9999
  servlet:
    context-path: /bootscoder  # 所有接口前缀为 /bootscoder

# 数据库和 Redis 配置
spring:
  datasource:
    url: jdbc:mysql://110.41.60.133:3306/redis-service?useSSL=true&serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    username: root
    password: root1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    connection:
      host: 110.41.60.133
      port: 6379
      password: root
#开启所有监控端点
management:
  endpoints:
    web:
      exposure:
        include: '*'

# mybatis 配置
mybatis:
  mapper-locations: classpath:com/example/demo/mapper/*Mapper.xml
  type-aliases-package: com.example.demo.entity
  configuration:
    map-underscore-to-camel-case: true  # 启用驼峰转换

logging:
  level:
    root: info
    com.example: debug   # 替换为你的包名
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# 自定义 springboot 配置
connectionInfo:
  email: 3552618816@qq.com
  wechat: Tsing0521

myconfig:
  moreAdvanceProfile:
    internship:
      - ChanJet-java-dataDepartment
      - YUNJie-backend-leader
    selfProject:
      - name: shopping
        tech: springboot+redis+mysql
      - name: PropertyManagementSystem
        tech: fastDFS